[[redirects]]
  from = "https://catsies.dev/*" 
  to = "https://blog.catsies.dev/:splat"
  status =  301
  force = true

[[redirects]]
  from = "https://catsies.netlify.com/*" 
  to = "https://blog.catsies.dev/:splat" 
  status = 301
  force = true
